 /* Main.ino file generated by New Project wizard
 *
 * Created:   Wed Mar 13 2019
 * Processor: Arduino Uno
 * Compiler:  Arduino AVR (Proteus)
 */
#define gas_Pin 12
#define flexPin A0
#define ledPin 3 


int gas_value;
int value;

void setup()
 { 
  
 Serial.begin(9600);
 pinMode(2,OUTPUT);
 pinMode(ledPin, OUTPUT);
 
 
 }

void loop()
 { // put your main code here, to run repeatedly:
value = digitalRead(flexPin);         //Read and save analog value from potentiometer
  Serial.println( value);               //Print value
  value = map(value, 900, 0, 200, 255);//Map value 0-1023 to 0-255 (PWM)
    Serial.print("    -HELMET UPDATE    ");
  analogWrite(ledPin, value);//Send PWM value to led
/*if(value==1)
{
  digitalWrite(3,HIGH);
  Serial.print("HELMET");
  }
  else
  {
    digitalWrite(3,LOW);
    Serial.print("NO HELMET");
    }
  //digitalWrite(ledPin,value);
  delay(100); 
*/
gas_value=digitalRead(gas_Pin);
//Serial.print(gas_value);
if(gas_value==1)
{
digitalWrite(2,HIGH);
//Serial.print(gas_value);
Serial.print("       NO ALCOHOL         ");
digitalWrite(1,HIGH);
}
else{
digitalWrite(2,LOW);
Serial.print("     ALCOHOL DETECTED           ");
digitalWrite(1,LOW);
delay(1000);
}
                         //Small delay
 }
